/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Author: Willy Decarpentrie (https://sketchfab.com/skudgee)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mech-drone-8d06874aac5246c59edb4adbe3606e0e
Title: Mech Drone
*/

import React, { useEffect, useRef } from "react";
import { useGLTF, useAnimations } from "@react-three/drei";
import scene from '../assets/3d/cuphead.glb'




function Fox({currentAnimation,...props}) {
  const group = useRef();
  const { nodes, materials, animations } = useGLTF(scene);
  const { actions } = useAnimations(animations, group);


  
useEffect(()=>{
    Object.values(actions).forEach((action)=>action.stop());
    if(actions[currentAnimation]){
        actions[currentAnimation].timeScale=1.5;
        actions[currentAnimation].play();
    }


},[actions,currentAnimation])

  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group
          name="Sketchfab_model"
          rotation={[-Math.PI / 2, 0, 0]}
          scale={0.491}
        >
          <group name="Root">
            <group name="Cuphead_Armature">
              <primitive object={nodes.Cuphead_Armature_rootJoint} />
              <skinnedMesh
                name="Cuphead_mesh_0"
                geometry={nodes.Cuphead_mesh_0.geometry}
                material={materials.cuphead}
                skeleton={nodes.Cuphead_mesh_0.skeleton}
              />
              <skinnedMesh
                name="Cuphead_mesh_1"
                geometry={nodes.Cuphead_mesh_1.geometry}
                material={materials.outline}
                skeleton={nodes.Cuphead_mesh_1.skeleton}
              />
              <group name="Cuphead_mesh" />
            </group>
          </group>
        </group>
      </group>
    </group>
  );
}



export default Fox;